version: '3.7'

services:
  modeling:
    build:
      context: .
    container_name: modeling
    restart: unless-stopped
    env_file:
      - .modeling.env
    ports:
      - 8500:8500

networks:
  default:
    name: codeclusters-prod
